# ---- Build -----------
#
#    docker  build -f Containerfile.QuidJS . -t QuidJS
#    podman  build -f Containerfile.QuidJS . -t QuidJS
#    buildah build -f Containerfile.QuidJS . -t QuidJS
#
# With some arguments:
#
#    docker build -f Containerfile.QuidJS --build-arg UID=1133 --build-arg URL=https://USR:PAT@github.com/org/private.git . -t QuidJS
#
# Extract the web static files from the container:
#
#     mv dist dist.old
#     docker create QuidJS  # this prints the container-ID to be used in the next commands
#     docker cp b66288ae5380b2138d17ea2bf44f8bdd4da73a2890f1a0ef6cae87e7dd8abd88:/dist dist
#     docker rm b66288ae5380b2138d17ea2bf44f8bdd4da73a2890f1a0ef6cae87e7dd8abd88
#     diff -rq dist.old dist
#     du -h dist.old dist | sort -h
#
# Build+Extract in one command line:
#
#    ( set -eux ; docker build -f Containerfile.QuidJS -t QuidJS . ; id="$(docker create QuidJS)" ; rm dist -fr ; docker cp "$id":/dist dist ; docker rm "$id" )

# ---- Run -------------
#
#    docker run --rm --name QuidJS QuidJS
#


# --------------------------------------------------------------------

# https://hub.docker.com/_/node
FROM docker.io/node:24-alpine

# Arguments to run NodeJS as unprivileged.
ARG UID=1122
ARG GID=${UID}

# Copy HTTPS root certificates (200 KB).
# Create user & group files.
RUN set -ex                                                         ;\
    mkdir -p                                 /target/cache          ;\
    mkdir -p                                 /target/config         ;\
    mkdir -p                                 /target/var/www        ;\
    mkdir -p                                 /target/etc/ssl/certs  ;\
    cp -a /etc/ssl/certs/ca-certificates.crt /target/etc/ssl/certs  ;\
    echo 'user:x:${UID}:${GID}::/:'      >   /target/etc/passwd     ;\
    echo 'user:x:${GID}:'                >   /target/etc/group

# Run as unprivileged
USER user:user

# Arguments to build and serve web files
ARG addr=http://localhost
ARG port=55222

WORKDIR /code

COPY package.json ./

RUN set -ex                         ;\
    yarn versions                   ;\
    yarn install --frozen-lockfile  ;\
    yarn cache clean

COPY index.html         \
    postcss.config.js   \
    tailwind.config.js  \
    tsconfig.json       \
    vite.config.ts     ./

COPY public  public
COPY src     src

RUN set -ex               ;\
    ls -lShA              ;\
    yarn build            ;\
    mv /code/dist /dist   ;\
    rm -r /code
